import {Badge} from "@/types/badges"

export const BADGES = {
    "20": {
        "id_badge": 20,
        "nom": "Commenter 10 avantages",
        "datetime": "2018-10-01 00:00:00",
        "type": "communautaire",
        "type_solo": "",
        "type_communautaire": "comment",
        "programmer_nb_rappel": 0,
        "mettre_nb_av_fav": 0,
        "partager_nb_av": 0,
        "noter_nb_av": 0,
        "poster_nb_comment": 10,
        "enregistrer_nb_av_parcours": 0,
        "like_nb_av": 0,
        "image": "comment_skin.svg",
        "nb_deblocage": null,
        "image_url": "https://backoffice.avantagesjeunes.com/uploads/badges/comment_skin.svg",
        "condition": "Poster 10 commentaires",
        "parcours_categories": false,
        "position": 1,
        // new fields
        "target": 10,
        "target_type": "comments"
    },
    "21": {
        "id_badge": 21,
        "nom": "Noter 10 avantages",
        "datetime": "2018-10-01 00:00:00",
        "type": "communautaire",
        "type_solo": "",
        "type_communautaire": "note",
        "programmer_nb_rappel": 0,
        "mettre_nb_av_fav": 0,
        "partager_nb_av": 0,
        "noter_nb_av": 10,
        "poster_nb_comment": 0,
        "enregistrer_nb_av_parcours": 0,
        "like_nb_av": 0,
        "image": "rate_yellow.svg",
        "nb_deblocage": null,
        "image_url": "https://backoffice.avantagesjeunes.com/uploads/badges/rate_yellow.svg",
        "condition": "Noter 10 avantages",
        "parcours_categories": false,
        "position": 12,
        // new fields
        "target": 10,
        "target_type": "notes"
    },
    "22": {
        "id_badge": 22,
        "nom": "Mettre 10 avantages en favoris",
        "datetime": "2018-10-01 00:00:00",
        "type": "solo",
        "type_solo": "favoris",
        "type_communautaire": "",
        "programmer_nb_rappel": 0,
        "mettre_nb_av_fav": 10,
        "partager_nb_av": 0,
        "noter_nb_av": 0,
        "poster_nb_comment": 0,
        "enregistrer_nb_av_parcours": 0,
        "like_nb_av": 0,
        "image": "fav_red.svg",
        "nb_deblocage": null,
        "image_url": "https://backoffice.avantagesjeunes.com/uploads/badges/fav_red.svg",
        "condition": "Ajouter 10 avantages à vos favoris",
        "parcours_categories": false,
        "position": 11,
        // new fields
        "target": 10,
        "target_type": "favoris"
    },
    "23": {
        "id_badge": 23,
        "nom": "Programmer 5 rappels",
        "datetime": "2018-10-01 00:00:00",
        "type": "solo",
        "type_solo": "rappel",
        "type_communautaire": "",
        "programmer_nb_rappel": 5,
        "mettre_nb_av_fav": 0,
        "partager_nb_av": 0,
        "noter_nb_av": 0,
        "poster_nb_comment": 0,
        "enregistrer_nb_av_parcours": 0,
        "like_nb_av": 0,
        "image": "bell_green.svg",
        "nb_deblocage": null,
        "image_url": "https://backoffice.avantagesjeunes.com/uploads/badges/bell_green.svg",
        "condition": "Programmer 5 rappels",
        "parcours_categories": false,
        "position": 13,
        // new fields
        "target": 5,
        "target_type": "rappels"
    },
    "24": {
        "id_badge": 24,
        "nom": "Enregistrer 1 avantage : Citoyenneté et solidarité",
        "datetime": "2018-10-01 15:56:54",
        "type": "solo",
        "type_solo": "parcours",
        "type_communautaire": "",
        "programmer_nb_rappel": 0,
        "mettre_nb_av_fav": 0,
        "partager_nb_av": 0,
        "noter_nb_av": 0,
        "poster_nb_comment": 0,
        "enregistrer_nb_av_parcours": 1,
        "like_nb_av": 0,
        "image": "save_purple.svg",
        "nb_deblocage": null,
        "image_url": "https://backoffice.avantagesjeunes.com/uploads/badges/save_purple.svg",
        "condition": "",
        "parcours_categories": false,
        "position": 4,
        // new fields
        "target": 1,
        "target_type": 1
    },
    "25": {
        "id_badge": 25,
        "nom": "Enregistrer 5 avantages : Cinéma, Musées, Loisirs, Musique, Mode",
        "datetime": "2018-10-01 15:59:59",
        "type": "solo",
        "type_solo": "parcours",
        "type_communautaire": "",
        "programmer_nb_rappel": 0,
        "mettre_nb_av_fav": 0,
        "partager_nb_av": 0,
        "noter_nb_av": 0,
        "poster_nb_comment": 0,
        "enregistrer_nb_av_parcours": 5,
        "like_nb_av": 0,
        "image": "save_purple.svg",
        "nb_deblocage": null,
        "image_url": "https://backoffice.avantagesjeunes.com/uploads/badges/save_purple.svg",
        "condition": "Dans \"Mes avantages utilisés\", enregistrer 5 avantages dans les rubriques : Cinéma, Musique, Mode, Loisirs, arts créatifs, Musées, patrimoine",
        "parcours_categories": [
            7,
            123,
            160,
            26,
            140
        ],
        "position": 7,
        // new fields
        "target": 5,
        "target_type": 1
    },
    "26": {
        "id_badge": 26,
        "nom": "Enregistrer 5 avantages : Cinéma, Concert, Festival, Livres,  Musées",
        "datetime": "2018-10-01 16:01:55",
        "type": "solo",
        "type_solo": "parcours",
        "type_communautaire": "",
        "programmer_nb_rappel": 0,
        "mettre_nb_av_fav": 0,
        "partager_nb_av": 0,
        "noter_nb_av": 0,
        "poster_nb_comment": 0,
        "enregistrer_nb_av_parcours": 5,
        "like_nb_av": 0,
        "image": "save_purple.svg",
        "nb_deblocage": null,
        "image_url": "https://backoffice.avantagesjeunes.com/uploads/badges/save_purple.svg",
        "condition": "Dans \"Mes avantages utilisés\", enregistrer 5 avantages dans les rubriques : Cinéma, Concerts, spectacles, théâtres, Festivals, manifestations, Livres, papeterie, Musées, patrimoine",
        "parcours_categories": [
            7,
            8,
            88,
            96,
            140
        ],
        "position": 6,
        // new fields
        "target": 5,
        "target_type": 1
    },
    "27": {
        "id_badge": 27,
        "nom": "Enregistrer 10 avantages : Loisirs, Plein Air, Articles sport, Discothèque, Loisirs et arts, Manif sportive, Parcs de loisirs, Sport d\\'hiver",
        "datetime": "2018-10-01 16:04:36",
        "type": "solo",
        "type_solo": "parcours",
        "type_communautaire": "",
        "programmer_nb_rappel": 0,
        "mettre_nb_av_fav": 0,
        "partager_nb_av": 0,
        "noter_nb_av": 0,
        "poster_nb_comment": 0,
        "enregistrer_nb_av_parcours": 10,
        "like_nb_av": 0,
        "image": "save_purple.svg",
        "nb_deblocage": null,
        "image_url": "https://backoffice.avantagesjeunes.com/uploads/badges/save_purple.svg",
        "condition": "Dans \"Mes avantages utilisés\", enregistrer 10 avantages dans les rubriques : Discothèque, Parc de loisirs, Sports d'hiver, Loisirs, arts créatifs, Manifestation sportive, Article de sport, Activité de loisirs",
        "parcours_categories": [
            15,
            62,
            146,
            26,
            90,
            13,
            141
        ],
        "position": 3,
        // new fields
        "target": 10,
        "target_type": 1
    },
    "28": {
        "id_badge": 28,
        "nom": "Enregistrer 5 avantages : Restauration et gourmandise",
        "datetime": "2018-10-01 16:05:57",
        "type": "solo",
        "type_solo": "parcours",
        "type_communautaire": "",
        "programmer_nb_rappel": 0,
        "mettre_nb_av_fav": 0,
        "partager_nb_av": 0,
        "noter_nb_av": 0,
        "poster_nb_comment": 0,
        "enregistrer_nb_av_parcours": 5,
        "like_nb_av": 0,
        "image": "save_purple.svg",
        "nb_deblocage": null,
        "image_url": "https://backoffice.avantagesjeunes.com/uploads/badges/save_purple.svg",
        "condition": "Dans \"Mes avantages utilisés\", enregistrer 5 avantages dans la rubrique : Restaurants et gourmandises",
        "parcours_categories": [
            163
        ],
        "position": 9,
        // new fields
        "target": 5,
        "target_type": 1
    },
    "29": {
        "id_badge": 29,
        "nom": "Enregistrer 5 avantages : Musées, Voyages, Plein air, Déplacement",
        "datetime": "2018-10-01 16:11:34",
        "type": "solo",
        "type_solo": "parcours",
        "type_communautaire": "",
        "programmer_nb_rappel": 0,
        "mettre_nb_av_fav": 0,
        "partager_nb_av": 0,
        "noter_nb_av": 0,
        "poster_nb_comment": 0,
        "enregistrer_nb_av_parcours": 5,
        "like_nb_av": 0,
        "image": "save_purple.svg",
        "nb_deblocage": null,
        "image_url": "https://backoffice.avantagesjeunes.com/uploads/badges/save_purple.svg",
        "condition": "Dans \"Mes avantages utilisés\", enregistrer 5 avantages dans les rubriques : Voyage, Déplacement, véhicule et permis, Musées, patrimoine",
        "parcours_categories": [
            87,
            153,
            140
        ],
        "position": 8,
        // new fields
        "target": 5,
        "target_type": 1
    },
    "30": {
        "id_badge": 30,
        "nom": "Enregistrer 10 avantages : Commerce et vie pratique",
        "datetime": "2018-10-01 16:20:06",
        "type": "solo",
        "type_solo": "parcours",
        "type_communautaire": "",
        "programmer_nb_rappel": 0,
        "mettre_nb_av_fav": 0,
        "partager_nb_av": 0,
        "noter_nb_av": 0,
        "poster_nb_comment": 0,
        "enregistrer_nb_av_parcours": 10,
        "like_nb_av": 0,
        "image": "save_purple.svg",
        "nb_deblocage": null,
        "image_url": "https://backoffice.avantagesjeunes.com/uploads/badges/save_purple.svg",
        "condition": "",
        "parcours_categories": false,
        "position": 2,
        // new fields
        "target": 10,
        "target_type": 1
    },
    "31": {
        "id_badge": 31,
        "nom": "Enregistrer 3 avantages : Informatique, Jeux, Téléphone",
        "datetime": "2018-10-01 16:21:16",
        "type": "solo",
        "type_solo": "parcours",
        "type_communautaire": "",
        "programmer_nb_rappel": 0,
        "mettre_nb_av_fav": 0,
        "partager_nb_av": 0,
        "noter_nb_av": 0,
        "poster_nb_comment": 0,
        "enregistrer_nb_av_parcours": 3,
        "like_nb_av": 0,
        "image": "save_purple.svg",
        "nb_deblocage": null,
        "image_url": "https://backoffice.avantagesjeunes.com/uploads/badges/save_purple.svg",
        "condition": "Dans \"Mes avantages utilisés\", enregistrer 3 avantages dans les rubriques : Informatique, Internet, Téléphone, Jeux, jouets",
        "parcours_categories": [
            156,
            164,
            158
        ],
        "position": 5,
        // new fields
        "target": 3,
        "target_type": 1
    },
    "32": {
        "id_badge": 32,
        "nom": "Liker 30 avantages",
        "datetime": "2018-10-01 16:53:29",
        "type": "solo",
        "type_solo": "like",
        "type_communautaire": "",
        "programmer_nb_rappel": 0,
        "mettre_nb_av_fav": 0,
        "partager_nb_av": 0,
        "noter_nb_av": 0,
        "poster_nb_comment": 0,
        "enregistrer_nb_av_parcours": 0,
        "like_nb_av": 30,
        "image": "like_blue.svg",
        "nb_deblocage": null,
        "image_url": "https://backoffice.avantagesjeunes.com/uploads/badges/like_blue.svg",
        "condition": "Liker 30 avantages",
        "parcours_categories": false,
        "position": 10,
        // new fields
        "target": 30,
        "target_type": "likes"
    }
} as unknown as {
    [key: string | number]: Badge
}
