# This workflow uses actions that are not certified by GitHub.
# THis workflow checks if the code can build
name: Code builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  build:
    name: Build Vue project
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Environnement
        run: npm install

      - name: Build code
        run: npm run build
